# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b0e6414de91cb85043dfa60efa742edd795049e3b8ced2f819d0ff6b094cad8de2192dbfe3d610528ac98c5555fcd8660e4aab1d8f09c66cb6770f73eb85884

test:
  secret_key_base: 8503ab8a8b49abf49908539807ef9d7ad5dd18b6bfdd01bc835c3a4c416b1a3efcab0ee6972b977ddcb6d93fa50acceda700872ab110fc00a3d5ed866a4e5685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
